spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxdb
    username: root # hier username von der Datenbank eintragen z.B. root
    password: root # hier password eintragen
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB		
  jpa:
    hibernate:
      ddl-auto: update  # Oder 'validate' oder 'none' je nach Phase
    show-sql: false
    open-in-view: false

  sql:
    init:
      mode: always

wxdb:
  import:
    cron: "0 0 1 * * ?"  # Uhrzeit f√ºr den Quartz-Job in Form einer CRON-Expression